[project]
name = "auto2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.scikit-build]
cmake.source-dir = "."

[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"